# Generated by Django 4.2.6 on 2024-11-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
