# Generated by Django 4.2.6 on 2024-11-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_admin_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
